---
releases:
- name: istio
  version: "((release_version))"
  # runtime config release versions cannot be 'latest'
  # http://bosh.io/docs/runtime-config.html#releases
- name: bosh-dns
  sha1: 9231b7c7d2f6aa85e0cb77fdeef7add54fdb3f1a
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=0.2.0
  version: 0.2.0
- name: bpm
  version: "0.2.0"
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.2.0
  sha1: f2bd126b17b3591160f501d88d79ccf0aba1ae54

addons:
- name: envoy-sidecar
  jobs:
  - name: bpm
    release: bpm
  - name: bosh-envoy
    release: istio
    consumes:
      bosh-pilot:
        from: bosh-pilot
        deployment: bosh-istio
  - name: bosh-dns
    release: bosh-dns
  - name: virtual-ip-agent
    release: istio
    consumes:
      bosh-pilot:
        from: bosh-pilot
        deployment: bosh-istio
  exclude:
    deployments:
    - bosh-istio
