---
releases:
- name: istio
  version: "((release_version))"
  # runtime config release versions cannot be 'latest'
  # http://bosh.io/docs/runtime-config.html#releases
- name: bosh-dns
  sha1: 9231b7c7d2f6aa85e0cb77fdeef7add54fdb3f1a
  url: https://bosh.io/d/github.com/cloudfoundry/bosh-dns-release?v=0.2.0
  version: 0.2.0

addons:
- name: envoy-sidecar
  jobs:
  - name: bosh-envoy
    release: istio
    consumes:
      bosh-pilot:
        from: bosh-pilot
        deployment: bosh-istio
  - name: bosh-dns
    release: bosh-dns
  - name: virtual-ip-agent
    release: istio
    consumes:
      bosh-pilot:
        from: bosh-pilot
        deployment: bosh-istio
  exclude:
    deployments:
    - bosh-istio
