---
name: sample-deployment

releases:
- name: boshy-istio
  version: latest
- name: bpm
  version: "0.2.0"
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.2.0
  sha1: f2bd126b17b3591160f501d88d79ccf0aba1ae54

instance_groups:
- name: apricot
  azs: [z1, z2, z3]
  instances: 5
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: example-httpbin
    release: boshy-istio
    properties:
      port: 9001
    expose_ports:
    - name: some-port
      number: 9001
  - name: bpm
    release: bpm

- name: banana
  azs: [z1, z2]
  instances: 3
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: example-httpbin
    release: boshy-istio
    properties:
      port: 9002
    expose_ports:
    - name: other-http
      number: 9002
  - name: bpm
    release: bpm

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  serial: false
  canaries: 1
  max_in_flight: 5
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000
